---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging
  labels:
    app: qawave
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qawave
      component: frontend
  template:
    metadata:
      labels:
        app: qawave
        component: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/hermanngeorge15/qawave-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: staging
  labels:
    app: qawave
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: qawave
    component: frontend
