package com.qawave.domain.model

import java.time.Instant

/**
 * Represents a test scenario - a concrete test case with ordered steps.
 * Scenarios are the core unit of test execution in QAWave.
 */
data class TestScenario(
    val id: ScenarioId,
    val suiteId: TestSuiteId?,
    val qaPackageId: QaPackageId?,
    val name: String,
    val description: String?,
    val steps: List<TestStep>,
    val tags: Set<String> = emptySet(),
    val source: ScenarioSource,
    val status: ScenarioStatus = ScenarioStatus.PENDING,
    val createdAt: Instant,
    val updatedAt: Instant
) {
    init {
        require(name.isNotBlank()) { "Scenario name cannot be blank" }
        require(steps.isNotEmpty()) { "Scenario must have at least one step" }
        require(steps.map { it.index }.toSet().size == steps.size) { "Step indices must be unique" }
    }

    /**
     * Returns the total number of steps in this scenario.
     */
    val stepCount: Int get() = steps.size

    /**
     * Returns steps sorted by index.
     */
    val orderedSteps: List<TestStep> get() = steps.sortedBy { it.index }

    /**
     * Returns operations (method + endpoint combinations) covered by this scenario.
     */
    val coveredOperations: Set<String> get() = steps.map { "${it.method} ${it.endpoint}" }.toSet()
}

/**
 * How the scenario was created.
 */
enum class ScenarioSource {
    /**
     * Generated by AI from requirements and OpenAPI spec.
     */
    AI_GENERATED,

    /**
     * Manually created by a user.
     */
    MANUAL,

    /**
     * Imported from external source (e.g., Postman collection).
     */
    IMPORTED,

    /**
     * Created from a template.
     */
    TEMPLATE
}

/**
 * Current status of the scenario.
 */
enum class ScenarioStatus {
    /**
     * Scenario is pending execution.
     */
    PENDING,

    /**
     * Scenario validation is in progress.
     */
    VALIDATING,

    /**
     * Scenario is valid and ready for execution.
     */
    READY,

    /**
     * Scenario validation failed.
     */
    INVALID,

    /**
     * Scenario is disabled and won't be executed.
     */
    DISABLED
}
