package com.qawave.infrastructure.messaging

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.qawave.domain.model.QaPackageId
import com.qawave.domain.model.QaPackageStatus
import java.time.Instant
import java.util.UUID

/**
 * Base interface for all domain events.
 * Uses Jackson polymorphic serialization for type handling.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type"
)
@JsonSubTypes(
    JsonSubTypes.Type(value = QaPackageCreatedEvent::class, name = "qa-package-created"),
    JsonSubTypes.Type(value = QaPackageStatusChangedEvent::class, name = "qa-package-status-changed"),
    JsonSubTypes.Type(value = QaPackageCompletedEvent::class, name = "qa-package-completed"),
    JsonSubTypes.Type(value = QaPackageFailedEvent::class, name = "qa-package-failed"),
    JsonSubTypes.Type(value = TestRunStartedEvent::class, name = "test-run-started"),
    JsonSubTypes.Type(value = TestRunCompletedEvent::class, name = "test-run-completed"),
    JsonSubTypes.Type(value = ScenarioGeneratedEvent::class, name = "scenario-generated"),
    JsonSubTypes.Type(value = ScenarioExecutedEvent::class, name = "scenario-executed")
)
sealed interface DomainEvent {
    val eventId: String
    val timestamp: Instant
    val aggregateId: String
}

/**
 * Event published when a new QA package is created.
 */
data class QaPackageCreatedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val packageName: String,
    val baseUrl: String,
    val triggeredBy: String
) : DomainEvent

/**
 * Event published when a QA package status changes.
 */
data class QaPackageStatusChangedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val previousStatus: String,
    val newStatus: String
) : DomainEvent

/**
 * Event published when a QA package completes successfully.
 */
data class QaPackageCompletedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val passedScenarios: Int,
    val failedScenarios: Int,
    val coveragePercentage: Double
) : DomainEvent

/**
 * Event published when a QA package fails.
 */
data class QaPackageFailedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val failureStatus: String,
    val errorMessage: String?
) : DomainEvent

/**
 * Event published when a test run starts.
 */
data class TestRunStartedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val packageId: String,
    val scenarioCount: Int
) : DomainEvent

/**
 * Event published when a test run completes.
 */
data class TestRunCompletedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val packageId: String,
    val passedSteps: Int,
    val failedSteps: Int,
    val durationMs: Long
) : DomainEvent

/**
 * Event published when a scenario is generated by AI.
 */
data class ScenarioGeneratedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val packageId: String,
    val scenarioName: String,
    val stepCount: Int
) : DomainEvent

/**
 * Event published when a scenario finishes execution.
 */
data class ScenarioExecutedEvent(
    override val eventId: String = UUID.randomUUID().toString(),
    override val timestamp: Instant = Instant.now(),
    override val aggregateId: String,
    val packageId: String,
    val scenarioName: String,
    val passed: Boolean,
    val durationMs: Long
) : DomainEvent
