name: Task Assignment
description: Assign a task to an agent
title: "[AGENT] Task: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Task Assignment
        Use this template to assign tasks to agents.

  - type: input
    id: task-id
    attributes:
      label: Task ID
      description: Reference from TODO.md
      placeholder: "P1-001"
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Assigned Agent
      options:
        - Backend
        - Frontend
        - DevOps
        - QA
        - Security
        - Database
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Describe the task in detail...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests written and passing
        - [ ] Documentation updated
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What must be completed first?
      placeholder: |
        Depends on: #issue-number
        Blocks: #issue-number

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any additional context or references
      placeholder: |
        See TECH_STACK.md section X
        Reference: BUSINESS_REQUIREMENTS.md section Y
