# ArgoCD Application for cert-manager
# Automatic TLS Certificate Management
#
# Components:
#   - cert-manager controller
#   - ClusterIssuers (Let's Encrypt staging/production)
#   - Certificate resources for QAWave domains
#
# Prerequisites:
#   1. nginx-ingress controller deployed
#   2. DNS configured for domains

---
# AppProject for infrastructure/security components
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure and Security Components
  sourceRepos:
    - 'https://charts.jetstack.io'
    - 'https://github.com/hermanngeorge15/qawave-automation.git'
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: qawave
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: cert-manager.io
      kind: '*'
    - group: networking.k8s.io
      kind: '*'

---
# Deploy cert-manager using Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app: infrastructure
    component: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.14.*"
    helm:
      releaseName: cert-manager
      valuesObject:
        # Install CRDs
        installCRDs: true

        # Replica count for HA
        replicaCount: 2

        # Resource limits
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Webhook configuration
        webhook:
          replicaCount: 2
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

        # CA Injector
        cainjector:
          replicaCount: 2
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi

        # Prometheus metrics
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
            interval: 60s

        # Pod disruption budgets
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Security context
        securityContext:
          runAsNonRoot: true

        # Global settings
        global:
          leaderElection:
            namespace: cert-manager

        # Logging
        extraArgs:
          - --logging-format=json
          - --v=2

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

---
# Deploy ClusterIssuers and Certificates
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  labels:
    app: infrastructure
    component: cert-manager-issuers
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy after cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/hermanngeorge15/qawave-automation.git
    targetRevision: main
    path: infrastructure/kubernetes/base/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
