/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUnauthorizedRouteImport } from './routes/_app/unauthorized'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScenariosRouteImport } from './routes/_app/scenarios'
import { Route as AppPackagesRouteImport } from './routes/_app/packages'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs.$runId'
import { Route as AppPackagesNewRouteImport } from './routes/_app/packages.new'
import { Route as AppPackagesPackageIdRouteImport } from './routes/_app/packages.$packageId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesNewRoute = AppPackagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppPackagesPackageIdRoute = AppPackagesPackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => AppPackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/packages': typeof AppPackagesRouteWithChildren
  '/scenarios': typeof AppScenariosRoute
  '/settings': typeof AppSettingsRoute
  '/unauthorized': typeof AppUnauthorizedRoute
  '/packages/$packageId': typeof AppPackagesPackageIdRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/packages': typeof AppPackagesRouteWithChildren
  '/scenarios': typeof AppScenariosRoute
  '/settings': typeof AppSettingsRoute
  '/unauthorized': typeof AppUnauthorizedRoute
  '/': typeof AppIndexRoute
  '/packages/$packageId': typeof AppPackagesPackageIdRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/packages': typeof AppPackagesRouteWithChildren
  '/_app/scenarios': typeof AppScenariosRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/unauthorized': typeof AppUnauthorizedRoute
  '/_app/': typeof AppIndexRoute
  '/_app/packages/$packageId': typeof AppPackagesPackageIdRoute
  '/_app/packages/new': typeof AppPackagesNewRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/packages'
    | '/scenarios'
    | '/settings'
    | '/unauthorized'
    | '/packages/$packageId'
    | '/packages/new'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/packages'
    | '/scenarios'
    | '/settings'
    | '/unauthorized'
    | '/'
    | '/packages/$packageId'
    | '/packages/new'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/packages'
    | '/_app/scenarios'
    | '/_app/settings'
    | '/_app/unauthorized'
    | '/_app/'
    | '/_app/packages/$packageId'
    | '/_app/packages/new'
    | '/_app/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unauthorized': {
      id: '/_app/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios': {
      id: '/_app/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages': {
      id: '/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/new': {
      id: '/_app/packages/new'
      path: '/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof AppPackagesNewRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/_app/packages/$packageId': {
      id: '/_app/packages/$packageId'
      path: '/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof AppPackagesPackageIdRouteImport
      parentRoute: typeof AppPackagesRoute
    }
  }
}

interface AppPackagesRouteChildren {
  AppPackagesPackageIdRoute: typeof AppPackagesPackageIdRoute
  AppPackagesNewRoute: typeof AppPackagesNewRoute
}

const AppPackagesRouteChildren: AppPackagesRouteChildren = {
  AppPackagesPackageIdRoute: AppPackagesPackageIdRoute,
  AppPackagesNewRoute: AppPackagesNewRoute,
}

const AppPackagesRouteWithChildren = AppPackagesRoute._addFileChildren(
  AppPackagesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPackagesRoute: typeof AppPackagesRouteWithChildren
  AppScenariosRoute: typeof AppScenariosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPackagesRoute: AppPackagesRouteWithChildren,
  AppScenariosRoute: AppScenariosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppIndexRoute: AppIndexRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
